### ISSUE TITLE
De/Serialize Vec<af::Array>

### ISSUE THREAD

**Issue by ghost** [shibii/arrayfire_serde#1]
I am trying to Serialize a `Vec<af::Array>`, but I cant get it working.
Here is an example of what I try to do:
```rust
#[derive(Serialize, Deserialize)]
struct test {
    #[serde(with = "arrayfire_serde")] // Works
    field1: af::Array,
    #[serde(with = "arrayfire_serde")] // Does not work
    field2: Vec<af::Array>,
}`

**Comment by shibii** [comment]
[This discussion](https://github.com/serde-rs/serde/issues/723) covers the general issue of handling remote serializable types inside collections.
